language:
  node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
before_install:
  - sh -c "$INIT"
script:
  - npm run build
  - npm test -- --coverageReporters=text-lcov | npx coveralls
