name: "ci"
on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - run: npm install
      - run: npm run check
      - run: npm run lint
      - run: npm run build
      - run: npm test -- --coverage

      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
